force-app/main/default/objects/Account/fields/Department_type__c.field-meta.xml
<CustomField>
    <fullName>Department_type__c</fullName>
    <label>Department type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Children</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Hospital.recordType-meta.xml
<RecordType>
    <fullName>Hospital</fullName>
    <active>true</active>
    <label>Hospital</label>
</RecordType>

force-app/main/default/objects/Case/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>Treatments</relationshipLabel>
    <relationshipName>Treatments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Treatments</relationshipLabel>
    <relationshipName>Treatments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance__c/fields/Covered_departments__c.field-meta.xml
<CustomField>
    <fullName>Covered_departments__c</fullName>
    <label>Covered departments</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reception</fullName>
            </value>
            <value>
                <fullName>Therapy</fullName>
            </value>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Psychiatric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Department_type__c.field-meta.xml
<CustomField>
    <fullName>Department_type__c</fullName>
    <label>Department type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Children</fullName>
            </value>
            <value>
                <fullName>Adult</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/InsuranceCompany__c.field-meta.xml
<CustomField>
    <fullName>InsuranceCompany__c</fullName>
    <label>InsuranceCompany</label>
    <referenceTo>InsuranceCompany__c</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InsuranceCompany__c/InsuranceCompany__c.object-meta.xml
<CustomObject>
    <label>InsuranceCompany</label>
    <nameField>
        <label>InsurenceCompany Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InsuranceCompanies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Unic number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Birthday_date__c.field-meta.xml
<CustomField>
    <fullName>Birthday_date__c</fullName>
    <label>Birthday date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hospital</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Hospital</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Treatment__c.field-meta.xml
<CustomField>
    <fullName>Treatment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Treatment</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public with sharing class TestDataFactory{
    public static List<Account> createHospitalsList(Integer amount, Boolean doInsert){
        List<Account> hospitalList = new List<Account>();
        for (Integer i = 0; i < amount; i++){
            hospitalList.add(new Account(Name = 'Test Hospital' + i));
        }
        if (doInsert){
            insert hospitalList;
        }
        return hospitalList;
    }

    public static List<Account> createHospitalsDepartmentList(Integer amount, List<Account> hospitalList, Boolean doInsert){
        List<Account> hospitalDepartmentList = new List<Account>();
        for (Integer i = 0; i < amount; i++){
            for (Integer j = 0; j < hospitalList.size(); j++){
                hospitalDepartmentList.add(new Account(Name = 'Test hospital department ' + i, Parent = hospitalList[j]));
            }
        }
        if (doInsert){
            insert hospitalDepartmentList;
        }
        return hospitalDepartmentList;
    }

    public static List<InsuranceCompany__c> createInsurenceCompanyList(Integer amount, Boolean doInsert){
        List<InsuranceCompany__c> insuranceCompaniesList = new List<InsuranceCompany__c>();
        for (Integer i = 0; i < amount; i++){
            insuranceCompaniesList.add(new InsuranceCompany__c(Name = 'Insurance company ' + i));
        }
        if (doInsert){
            insert insuranceCompaniesList;
        }
        return insuranceCompaniesList;
    }

    public static List<Contact> createDoctorsList(Integer amount, List<Account> hospitalDepartmentList, Boolean doInsert){
        List<Contact> doctorsList = new List<Contact>();
        for (Integer i = 0; i < amount; i++){
            for (Integer j = 0; j < hospitalDepartmentList.size(); j++){
                doctorsList.add(new Contact(AccountId = hospitalDepartmentList[j].Id, FirstName = 'FirstName D ' + i, LastName = 'LastName D ' + i));
            }
        }
        if (doInsert){
            insert doctorsList;
        }
        return doctorsList;
    }

    public static List<Patient__c> createPatientList(Integer amount, List<Account> hospitalList, Boolean doInsert){
        List<Patient__c> patientList = new List<Patient__c>();
        for (Integer i = 0; i < amount; i++){
            for (Integer j = 0; j < hospitalList.size(); j++){
                patientList.add(new Patient__c(First_Name__c = 'Test Patient FN ' + i, Last_Name__c = 'Last name ' + i, Hospital__r = hospitalList[j], Birthday_date__c = Date.newInstance(1960, 2, 17)));
            }
        }
        if (doInsert){
            insert patientList;
        }
        return patientList;
    }

    public static List<Insurance__c> createInsuranceList(Integer amount, Decimal insuranceAmount, List<InsuranceCompany__c> isuranceCompanyList, List<Patient__c> patientList, Boolean doInsert){
        List<Insurance__c> insuranceList = new List<Insurance__c>();
        for (Integer i = 0; i < amount; i++){
            for (Integer j = 0; j < isuranceCompanyList.size(); j++){
                for (Integer k = 0; k < patientList.size(); k++){
                    insuranceList.add(new Insurance__c(Amount__c = insuranceAmount, Department_type__c = 'Adult', Covered_departments__c = 'Therapy', InsuranceCompany__c = isuranceCompanyList[j].Id, Patient__c = patientList[k].Id));
                }

            }
        }
        if (doInsert){
            insert insuranceList;
        }
        return insuranceList;
    }

    public static List<Case> createTreatmentList(Integer amount, List<Account> hospitalDepartmentList, List<Contact> doctorsList, List<Patient__c> patientList, List<Insurance__c> insuranceList, Boolean doInsert){
        List<Case> treatmentList = new List<Case>();
        for (Integer i = 0; i < amount; i++){
            for (Integer j = 0; j < insuranceList.size(); j++){
                for (Integer k = 0; k < patientList.size(); k++){
                    for (Integer h = 0; h < doctorsList.size(); h++){
                        for (Integer p = 0; p < hospitalDepartmentList.size(); p++){
                            treatmentList.add(new Case(Insurance__c = insuranceList[j].Id, Patient__c = patientList[k].Id, ContactId = doctorsList[h].Id, AccountId = hospitalDepartmentList[p].Id));
                        }
                    }
                }
            }
        }
        if (doInsert){
            insert treatmentList;
        }
        return treatmentList;
    }

    public static List<Receipt__c> createReceiptsList(Integer amount, List<Case> treatmentList, List<Patient__c> patientList, List<Insurance__c> isuranceList, Boolean doInsert){
        List<Receipt__c> receiptList = new List<Receipt__c>();
        for (Integer i = 0; i < amount; i++){
            for (Integer j = 0; j < treatmentList.size(); j++){
                for (Integer k = 0; k < patientList.size(); k++){
                    for (Integer h = 0; h < isuranceList.size(); h++){
                        receiptList.add(new Receipt__c(Treatment__c = treatmentList[j].Id, Patient__c = patientList[k].Id, Insurance__r = isuranceList[h]));
                    }
                }
            }
        }
        if (doInsert){
            insert receiptList;
        }
        return receiptList;
    }

}