force-app/main/default/objects/Account/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>Psychiatric</fullName>
            </value>
            <value>
                <fullName>Reception</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Therapy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Department_type__c.field-meta.xml
<CustomField>
    <fullName>Department_type__c</fullName>
    <label>Department type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Children</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Doctor_payments_to_receive_bonus__c.field-meta.xml
<CustomField>
    <fullName>Doctor_payments_to_receive_bonus__c</fullName>
    <label>Doctor payments to receive bonus</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Best_doctor_of_the_month__c.field-meta.xml
<CustomField>
    <fullName>Best_doctor_of_the_month__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Best doctor of the month</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Payments_amount__c.field-meta.xml
<CustomField>
    <fullName>Payments_amount__c</fullName>
    <label>Payments amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Department__mdt/Department__mdt.object-meta.xml
<CustomObject>
    <label>Department</label>
    <pluralLabel>Departments</pluralLabel>
</CustomObject>

force-app/main/default/objects/Department__mdt/fields/Bonus_amount__c.field-meta.xml
<CustomField>
    <fullName>Bonus_amount__c</fullName>
    <label>Bonus amount for «Best doctor»</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Department__mdt/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Gastroenterology</fullName>
                <default>true</default>
                <label>Gastroenterology</label>
            </value>
            <value>
                <fullName>Psychiatric</fullName>
            </value>
            <value>
                <fullName>Reception</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Therapy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Department_type__mdt/Department_type__mdt.object-meta.xml
<CustomObject>
    <label>Department type</label>
    <pluralLabel>Department types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Department_type__mdt/fields/Bonus_rate__c.field-meta.xml
<CustomField>
    <fullName>Bonus_rate__c</fullName>
    <label>Bonus rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Department_type__mdt/fields/Department_type__c.field-meta.xml
<CustomField>
    <fullName>Department_type__c</fullName>
    <label>Department type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Children</fullName>
                <default>true</default>
                <label>Children</label>
            </value>
            <value>
                <fullName>Adult</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Department_Type_Department__mdt/Department_Type_Department__mdt.object-meta.xml
<CustomObject>
    <label>Department Type Department</label>
    <pluralLabel>Department Type Departments</pluralLabel>
</CustomObject>

force-app/main/default/objects/Department_Type_Department__mdt/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__mdt</referenceTo>
    <relationshipLabel>Department Type Departments</relationshipLabel>
    <relationshipName>Department_Type_Departments</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Department_Type_Department__mdt/fields/Department_type__c.field-meta.xml
<CustomField>
    <fullName>Department_type__c</fullName>
    <label>Department type</label>
    <referenceTo>Department_type__mdt</referenceTo>
    <relationshipLabel>Department Type Departments</relationshipLabel>
    <relationshipName>Department_Type_Departments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/GreetingNotification.cls
// 4.    Create a scheduled process that runs every last day of the moth at 11 pm:
// 4.1    Create task for “Best doctor” with congrats text “Congratulations! You are the best doctor of the month and will receive the bonus!” and populate Bonus field [“Payments for getting bonus” (from doctor field) * “Bonus rate” (from metadata settings)]
// 4.2    Clear “Payments amount” and uncheck “Best doctor of the month” for all Doctor objects
public with sharing class GreetingNotification implements Schedulable{
    public void scheduleProcess(){
        String cronExpression = '0 0 0 L * ?'; 
        System.schedule('GreetingNotification Job', cronExpression, this);
    }

    public void execute(SchedulableContext context){
        notification();
    }

    public static void notification(){
        List<Contact> bestDoctorsOfMonthList = [SELECT Id, Best_doctor_of_the_month__c, Email, Payments_amount__c, AccountId, Account.Department__c, Account.Department_type__c, Account.Doctor_payments_to_receive_bonus__c
                                                FROM Contact
                                                WHERE Best_doctor_of_the_month__c = TRUE];

        List<String> doctorsEmailsList = new List<String>();

        List<Department_Type_Department__mdt> departmentMetadata = Department_Type_Department__mdt.getAll().values();

        List<Task> bonusPaymentsTask = new List<Task>();

        for (Contact doctor_i : bestDoctorsOfMonthList){
            List<Department_Type_Department__mdt> doctorsDepartmentMetadataList = [SELECT Department__r.Label, Department__r.Bonus_amount__c, Department_Type__r.Label, Department_Type__r.Bonus_rate__c
                                                                                   FROM Department_Type_Department__mdt
                                                                                   WHERE Department__r.Label = :doctor_i.Account.Department__c AND Department_Type__r.Label = :doctor_i.Account.Department_type__c];
            if (!doctorsDepartmentMetadataList.isEmpty()){
                Decimal bonus = doctor_i.Account.Doctor_payments_to_receive_bonus__c * doctorsDepartmentMetadataList[0].Department_Type__r.Bonus_rate__c;
                bonusPaymentsTask.add(new Task(WhoId = doctor_i.Id, WhatId = doctor_i.AccountId, Subject = 'Assign bonus', Bonus__c = bonus));
            }
            if (doctor_i.Email != null){
                doctorsEmailsList.add(doctor_i.Email);
            }

        }
        sendGreetingMessage(doctorsEmailsList);


        Database.SaveResult[] results = Database.insert (bonusPaymentsTask, true);

        ClearAllDoctorsFieldBatch batch = new ClearAllDoctorsFieldBatch();
        Id batchId = Database.executeBatch(batch);
    }

    @future(callout = true)
    public static void sendGreetingMessage(List<String> emailAddresses){
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(emailAddresses);
        email.setSubject('Best doctor');
        email.setHtmlBody('Congratulations! You are the best doctor of the month and will receive the bonus!');

        Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[]{ email });

        for (Messaging.SendEmailResult result : results){
            if (result.isSuccess()){
                System.debug('Email sent successfully');
            } else{
                System.debug('Error sending email: ' + result.getErrors()[0].getMessage());
            }
        }
    }

}