force-app/main/default/objects/Account/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>Psychiatric</fullName>
            </value>
            <value>
                <fullName>Reception</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Therapy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Department_type__c.field-meta.xml
<CustomField>
    <fullName>Department_type__c</fullName>
    <label>Department type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Children</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Doctor_payments_to_receive_bonus__c.field-meta.xml
<CustomField>
    <fullName>Doctor_payments_to_receive_bonus__c</fullName>
    <label>Doctor payments to receive bonus</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Best_doctor_of_the_month__c.field-meta.xml
<CustomField>
    <fullName>Best_doctor_of_the_month__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Best doctor of the month</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GreetingNotificationTest.cls
@IsTest
public with sharing class GreetingNotificationTest{
    private static final String CRON_EXP = '0 0 0 L * ?';
    @TestSetup
    static void makeData(){
        Test.setMock(HttpCalloutMock.class, new EmptyCalloutMock());
        List<Account> hospitalList = TestDataFactory.createHospitalsList(1, true);
        List<Account> hospitalDepartmentList = TestDataFactory.createHospitalsDepartmentList(1, hospitalList, false);
        hospitalDepartmentList[0].Department__c = 'Surgery';
        hospitalDepartmentList[0].Department_type__c = 'Adult';
        hospitalDepartmentList[0].Doctor_payments_to_receive_bonus__c = 300;
        insert hospitalDepartmentList;

        List<Contact> doctorsList = TestDataFactory.createDoctorsList(3, hospitalDepartmentList, false);
        for (Integer i = 0; i < doctorsList.size(); i++){
            if (i == 0){
                doctorsList[i].Best_doctor_of_the_month__c = true;
                doctorsList[i].Email = 'bestdoctor' + i + '@gmail.com';
            } else{
                doctorsList[i].Best_doctor_of_the_month__c = false;
                doctorsList[i].Email = 'looserofmonth' + i + '@gmail.com';
            }
        }
        insert doctorsList;
    }

    @IsTest
    static void testMethodName(){

        Test.startTest();
        System.schedule('Greeting notification', CRON_EXP, new GreetingNotification());
        Test.stopTest();

        List<Contact> bestDoctor = [SELECT Id, AccountId
                                    FROM Contact
                                    WHERE Best_doctor_of_the_month__c = true];
        System.assertEquals(1, bestDoctor.size());

        List<Task> taskList = [SELECT Id, WhoId, WhatId, Subject, Bonus__c
                               FROM Task
                               WHERE WhoId = :bestDoctor[0].Id AND WhatId = :bestDoctor[0].AccountId];
        System.assertEquals(1, taskList.size());
        System.assertEquals(600, taskList[0].Bonus__c);
    }

}