force-app/main/default/objects/Account/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>Psychiatric</fullName>
            </value>
            <value>
                <fullName>Reception</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Therapy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Department_type__c.field-meta.xml
<CustomField>
    <fullName>Department_type__c</fullName>
    <label>Department type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Children</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Hospital.recordType-meta.xml
<RecordType>
    <fullName>Hospital</fullName>
    <active>true</active>
    <label>Hospital</label>
</RecordType>

force-app/main/default/objects/Case/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Treatments</relationshipLabel>
    <relationshipName>Treatments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Unic number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Birthday_date__c.field-meta.xml
<CustomField>
    <fullName>Birthday_date__c</fullName>
    <label>Birthday date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHelperTest.cls
@isTest
public with sharing class CaseTriggerHelperTest{
    @IsTest
    static void caseInsertTest(){

        Test.setMock(HttpCalloutMock.class, new EmptyCalloutMock());
        List<Account> hospitalList = TestDataFactory.createHospitalsList(1, true);
        List<Account> hospitalDepartmentList = TestDataFactory.createHospitalsDepartmentList(3, hospitalList, false);
        hospitalDepartmentList[0].Department_type__c = 'Children';
        hospitalDepartmentList[0].Department__c = 'Surgery';
        hospitalDepartmentList[1].Department_type__c = 'Adult';
        hospitalDepartmentList[1].Department__c = 'Psychiatric';
        hospitalDepartmentList[2].Department_type__c = 'Adult';
        hospitalDepartmentList[2].Department__c = 'Therapy';
        insert hospitalDepartmentList;
        List<Patient__c> patientList = TestDataFactory.createPatientList(2, hospitalList, false);
        patientList[0].Birthday_date__c = Date.valueOf('2008-9-25');
        patientList[0].First_Name__c = 'Young';
        patientList[1].Birthday_date__c = Date.valueOf('2000-10-13');
        patientList[1].First_Name__c = 'Old';
        insert patientList;

        List<Case> treatmentList = new List<Case>();
        for (Integer i = 0; i < 4; i++){
            treatmentList.add(new Case());

        }
        treatmentList[0].Patient__c = patientList[0].Id;
        treatmentList[0].AccountId = hospitalDepartmentList[0].Id;
        treatmentList[1].Patient__c = patientList[0].Id;
        treatmentList[1].AccountId = hospitalDepartmentList[1].Id;
        treatmentList[2].Patient__c = patientList[1].Id;
        treatmentList[2].AccountId = hospitalDepartmentList[0].Id;
        treatmentList[3].Patient__c = patientList[1].Id;
        treatmentList[3].AccountId = hospitalDepartmentList[2].Id;
        System.debug('treatmentList: ' + treatmentList);
        Test.startTest();
        List<Database.SaveResult> insertResults = Database.insert (treatmentList, false);
        Test.stopTest();
        System.debug('Case trigger helper test !!!!!!!!!!!!!!');

        System.assertEquals(insertResults[0].isSuccess(), true);
        System.assertEquals(insertResults[1].isSuccess(), false);
        System.assertEquals(insertResults[1].getErrors()[0].getMessage(), 'Check Hospital department – patient age is not matched with department type!');
        System.assertEquals(insertResults[2].isSuccess(), false);
        System.assertEquals(insertResults[2].getErrors()[0].getMessage(), 'Check Hospital department – patient age is not matched with department type!');
        System.assertEquals(insertResults[3].isSuccess(), true);
    }

}