force-app/main/default/objects/Account/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>Psychiatric</fullName>
            </value>
            <value>
                <fullName>Reception</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Therapy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Department_type__c.field-meta.xml
<CustomField>
    <fullName>Department_type__c</fullName>
    <label>Department type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Children</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Hospital.recordType-meta.xml
<RecordType>
    <fullName>Hospital</fullName>
    <active>true</active>
    <label>Hospital</label>
</RecordType>

force-app/main/default/objects/Case/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>Treatments</relationshipLabel>
    <relationshipName>Treatments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Treatments</relationshipLabel>
    <relationshipName>Treatments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance__c/fields/Covered_departments__c.field-meta.xml
<CustomField>
    <fullName>Covered_departments__c</fullName>
    <label>Covered departments</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reception</fullName>
            </value>
            <value>
                <fullName>Therapy</fullName>
            </value>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Psychiatric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Department_type__c.field-meta.xml
<CustomField>
    <fullName>Department_type__c</fullName>
    <label>Department type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Children</fullName>
            </value>
            <value>
                <fullName>Adult</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Unic number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>FLOOR((TODAY()+1  - Birthday_date__c)/365.25)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHelper.cls
//7.    When Case is saved, create a validation for populated Hospital department – check Department type based on patient age and if the Hospital department is not valid – don’t save record and show error message “Check Hospital department – patient age is not matched with department type!”
// 8.    When Case is saved validate populated insurance – check that filled insurance can cover this case (based on Insurance Covered departments field)
public with sharing class CaseTriggerHelper extends TriggerHandler{
    protected override void beforeInsert(){
        checkHospitalDepartment((List<Case>)Trigger.new );
        validatePopulatedInsurance(Trigger.new );
    }

    private static void checkHospitalDepartment(List<Case> newTreatmentList){
        Set<Id> patientIdSet = new Set<Id>();
        Set<Id> hospitalDepartmentSet = new Set<Id>();

        for (Case treatment_i : newTreatmentList){
            patientIdSet.add(treatment_i.Patient__c);
            hospitalDepartmentSet.add(treatment_i.AccountId);
        }

        Map<Id, Patient__c> patientMap = new Map<Id, Patient__c>([SELECT Id, Age__c
                                                                  FROM Patient__c
                                                                  WHERE Id IN:patientIdSet]);

        Map<Id, Account> departmentMap = new Map<Id, Account>([SELECT Id, Department__c, Department_type__c
                                                               FROM Account
                                                               WHERE Id IN:hospitalDepartmentSet]);

        for (Case treatment_i : newTreatmentList){
            Patient__c patient = patientMap.get(treatment_i.Patient__c);
            Account department = departmentMap.get(treatment_i.AccountId);

            Boolean isPatientUnderage = patient.Age__c < 18;
            Boolean isAdultDepartment = department.Department_type__c == 'Adult' || department.Department__c == 'Psychiatric';
            Boolean isChildrenDepartment = department.Department_type__c == 'Children';

            if ((isPatientUnderage && isAdultDepartment) || (!isPatientUnderage && isChildrenDepartment)){
                treatment_i.AccountId.addError('Check Hospital department – patient age is not matched with department type!');
            }
        }
    }

    private static void validatePopulatedInsurance(List<Case> newTreatmentList){
        Set<Id> insuranceIdsSet = new Set<Id>();
        Set<Id> hospitalDepartmentSet = new Set<Id>();
        for (Case treatment_i : newTreatmentList){
            insuranceIdsSet.add(treatment_i.Insurance__c);
            hospitalDepartmentSet.add(treatment_i.AccountId);
        }
        Map<Id, Insurance__c> insuranceMap = new Map<Id, Insurance__c>([SELECT Id, Covered_departments__c, Department_type__c
                                                                        FROM Insurance__c
                                                                        WHERE Id IN:insuranceIdsSet]);

        List<Account> hospitalDepartmentsList = [SELECT Id, Department__c, Department_type__c
                                                 FROM Account
                                                 WHERE Id IN:hospitalDepartmentSet];
        Map<Id, Account> departmentMap = new Map<Id, Account>(hospitalDepartmentsList);
        for (Case treatment_i : newTreatmentList){
            if (!insuranceMap.get(treatment_i.Insurance__c).Covered_departments__c.contains(departmentMap.get(treatment_i.AccountId).Department__c) || insuranceMap.get(treatment_i.Insurance__c).Department_type__c != departmentMap.get(treatment_i.AccountId).Department_type__c){
                treatment_i.Insurance__c.addError('Insurance not covered this department or department type');
            }
        }
    }

}