force-app/main/default/objects/Contact/fields/Best_doctor_of_the_month__c.field-meta.xml
<CustomField>
    <fullName>Best_doctor_of_the_month__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Best doctor of the month</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Payments_amount__c.field-meta.xml
<CustomField>
    <fullName>Payments_amount__c</fullName>
    <label>Payments amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ClearAllDoctorsFieldBatchTest.cls
@isTest
public with sharing class ClearAllDoctorsFieldBatchTest{
    @TestSetup
    public static void makeData(){
        Test.setMock(HttpCalloutMock.class, new EmptyCalloutMock());
        List<Account> hospitalList = TestDataFactory.createHospitalsList(1, true);
        List<Account> hospitalDepartmentList = TestDataFactory.createHospitalsDepartmentList(1, hospitalList, true);
        List<Contact> doctorsList = TestDataFactory.createDoctorsList(112, hospitalDepartmentList, false);
        for (Integer i = 0; i < doctorsList.size(); i++){
            if (i < 2){
                doctorsList[i].Payments_amount__c = 0;
                doctorsList[i].Best_doctor_of_the_month__c = false;
            } else if (i == 2){
                doctorsList[i].Best_doctor_of_the_month__c = true;
                doctorsList[i].Payments_amount__c = 500;
            } else{
                doctorsList[i].Best_doctor_of_the_month__c = false;
                doctorsList[i].Payments_amount__c = 100;
            }

        }
        insert doctorsList;
    }

    @IsTest
    static void clearAllDoctorsFieldTest(){

        Test.startTest();
        Id batchId = Database.executeBatch(new ClearAllDoctorsFieldBatch());
        Test.stopTest();

        AsyncApexJob job = [SELECT Id, Status, JobItemsProcessed
                            FROM AsyncApexJob
                            WHERE Id = :batchId];
        System.assertEquals(1, job.JobItemsProcessed);
        System.assertEquals('Completed', job.Status);

        List<Contact> doctorsList = [SELECT Id
                                     FROM Contact
                                     WHERE Payments_amount__c = 0 AND Best_doctor_of_the_month__c = false];

        System.assertEquals(112, doctorsList.size(), 'Unexpected  result. Doctors num of records must be 112');
    }

}